version: '3'
services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5460:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_development

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails db:create db:migrate && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/app_development
      CABLE_DATABASE_URL: postgres://postgres:password@db:5432/app_development
      RAILS_ENV: development
      OPENAI_ACCESS_TOKEN: ${OPENAI_ACCESS_TOKEN}
    env_file:
      - .env

volumes:
  postgres_data:
